train_config:
  batch_size: 4
  obs_len: 8
  pred_len: 12
  fps: 2.5
  num_epoch: 100
  hidden_size: 128
  offset_mode: True
  log_dir: "None"
  seed: 42

dataset_config:
  fps: 60
  joint_num: 17
  train_dataset_path: "estimated_3d_joints/video_0_joint_3d_.npy"
  eval_dataset_path: "estimated_3d_joints/video_0_joint_3d_.npy"